name: Build and Push to GHCR

on:
  push:
    branches: [ main ] # Срабатывает при пуше в ветку main

env:
  REGISTRY: ghcr.io
  # Используем github.repository_owner, чтобы автоматически получить имя пользователя
  IMAGE_NAME: web-ssh-client

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
        # Прописываем путь вручную маленькими буквами
          tags: ghcr.io/dnikulshin/web-ssh-client:latest

      - name: Clean up old images
        # Опционально: удаляет старые слои, чтобы не копились (бесплатный лимит GHCR — 500МБ)
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.IMAGE_NAME }}
          min-versions-to-keep: 3
